# Java release used for source compatibility, API compatibility and bytecode
javacRelease=17

# Release Configuration
releaseVersion=1.941
releaseFileParentDir=yacy
privateKeyFile=private.key

# defining some file/directory access rights
accessRightsDir=755
accessRightsExecutable=755
accessRightsFile=644

