<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://yacy:8080/soap/status" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://yacy:8080/soap/status" xmlns:intf="http://yacy:8080/soap/status" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><!--WSDL created by Apache Axis version: 1.2RC2
Built on Nov 16, 2004 (12:19:44 EST)-->
  <wsdl:message name="networkResponse">
    <wsdl:part name="networkReturn" type="apachesoap:Document"/>
  </wsdl:message>
  <wsdl:message name="networkRequest">
  </wsdl:message>
  <wsdl:portType name="StatusService">
    <wsdl:operation name="network">
      <wsdl:input message="impl:networkRequest" name="networkRequest"/>
      <wsdl:output message="impl:networkResponse" name="networkResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="statusSoapBinding" type="impl:StatusService">
    <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="network">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="networkRequest">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://services.soap.anomic.de" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="networkResponse">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://yacy:8080/soap/status" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="StatusServiceService">
    <wsdl:port binding="impl:statusSoapBinding" name="status">
      <wsdlsoap:address location="http://yacy:8080/soap/status"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>