apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yacy.fullname" . }}
  labels:
    {{- include "yacy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.yacy.adminPassword }}
  admin-password: {{ .Values.yacy.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ "yacy" | b64enc | quote }}
  {{- end }}