<p><form action="SettingsAck_p.html" method="post" enctype="multipart/form-data">
<fieldset><legend id="admin">Administration Account Settings</legend>
<p>This is the account that restricts access to this 'Settings' page. If you have not customized it yet, you should do so now:
<p><table border="0" cellspacing="5">
  <tr valign="top">
    <td>Account Name:</td><td><input name="adminuser" type="text" size="16" maxlength="16" value="#[adminuser]#"></td>
  </tr>
  <tr valign="top">
    <td>Password:</td>
    <td><input name="adminpw1" type="password" size="16" maxlength="16" value=""></td></tr>
  <tr valign="top">
    <td>Password (repeat same as above):</td>
    <td><input name="adminpw2" type="password" size="16" maxlength="16" value=""></td>
  </tr>
  <tr valign="top">
    <td colspan="2"><input type="submit" name="adminaccount" value="submit"></td>
  </tr>
</table>
</fieldset>
</form><br>